# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_archivo', models.CharField(max_length=70, unique=True)),
            ],
        ),
    ]
