# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmanagement', '0002_auto_20160613_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datefile',
            name='id',
        ),
        migrations.AlterField(
            model_name='datefile',
            name='fecha_archivo',
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
        ),
    ]
