# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmanagement', '0003_auto_20160613_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefile',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
