# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmanagement', '0004_auto_20160614_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFileRest',
            fields=[
                ('fecha_archivo', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('archivo', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
